### ISSUE TITLE
Comentarios

### ISSUE THREAD

**Issue by nicosoutn2014** [andresemartinez/gdd-UberFrba#1]
Gestionar los siguientes cambios en el 'script_creacion_inicial.sql':

1) Agregar CLIE_CP VARCHAR(10) NOT NULL en la tabla CLIENTE.
2) Agregar las FUNCIONALIDADES definidas.
3) Chequear la migración de Turnos. Estan Duplicados

**Comment by andresemartinez** [comment]
Respuestas:

1. Existe actualmente CLIE_CODIGO_POSTAL CHAR(8) en la tabla CLIENTE. Lo puedo cambiar a 
CLIE_CP VARCHAR(10) si te parece mejor pero no puedo ponerle NOT NULL ya que ese dato no 
viene en la migración y no lo puedo inventar. Lo que no entiendo es porque un VARCHAR(10) si se 
sabe que un código pistan en argentina son 8 caracteres. Confirmarme que hacemos.

2. Funcionalidades agregadas:
- ABM de Rol - Administrador
- Login y Seguridad - Todos
- Registro de Usuario - Administrador
- ABM de Cliente - Administrador
- ABM de Automóvil - Administrador
- ABM de Chofer - Administrador
- Registro de Viajes - Chofer
- Rendición de cuenta del chofer - Administrador
- Facturación a Cliente - Administrador
- Listado Estadístico - Administrador

3. Acabo de correr el script y no me estaría trayendo turnos duplicados:
1	16	24	Turno Noche	0.85	8.50	1
2	8	16	Turno Tarde	0.73	7.30	1
3	0	8	Turno Mañna	0.73	7.30	1
¿Cuales te trae duplicados a vos?

**Comment by nicosoutn2014** [comment]
1)Dale ponele clie_cp char(8).
2)Funcionalidades ok.
3)Borre todo y volví a correrlo y me da bien, se ve que antes la corri 2
veces.

Necesito una mano con el query de modificar un vehículo. Hay q tener en
cuenta que aunq se haya corregido una simple letra en la modificación el
sistema actualiza todos los campos (sino hay q hacer un método que
verifique que campos cambiaron y actualizar solo esos pero es un re
quilombo). Hay que tener en cuenta q al modificar un vehículo, en el peor
de los casos hay que modificar el chofer, el turno (vehículo_chofer) y el
modelo (si es q el nuevo modelo ingresado existe ya en la tabla y tené un
Id existente) en este último caso por ahora hice que el sistema tire error,
q opinas?

El 11 jun. 2017 2:03 p. m., "Andres Martinez" <notifications@github.com>
escribió:

Respuestas:

   1.

   Existe actualmente CLIE_CODIGO_POSTAL CHAR(8) en la tabla CLIENTE. Lo
   puedo cambiar a
   CLIE_CP VARCHAR(10) si te parece mejor pero no puedo ponerle NOT NULL ya
   que ese dato no
   viene en la migración y no lo puedo inventar. Lo que no entiendo es
   porque un VARCHAR(10) si se
   sabe que un código pistan en argentina son 8 caracteres. Confirmarme que
   hacemos.
   2.

   Funcionalidades agregadas:


   - ABM de Rol - Administrador
   - Login y Seguridad - Todos
   - Registro de Usuario - Administrador
   - ABM de Cliente - Administrador
   - ABM de Automóvil - Administrador
   - ABM de Chofer - Administrador
   - Registro de Viajes - Chofer
   - Rendición de cuenta del chofer - Administrador
   - Facturación a Cliente - Administrador
   - Listado Estadístico - Administrador


   1. Acabo de correr el script y no me estaría trayendo turnos duplicados:
   1 16 24 Turno Noche 0.85 8.50 1
   2 8 16 Turno Tarde 0.73 7.30 1
   3 0 8 Turno Mañna 0.73 7.30 1
   ¿Cuales te trae duplicados a vos?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/andresemartinez/gdd-UberFrba/issues/1#issuecomment-307642415>,
or mute the thread

**Comment by andresemartinez** [comment]
Que al modificar un campo de la tabla se actualicen todos no me parece mal, es más fácil. Ahora, que al editar el vehículo se modifique el chofer el turno y el modelo no me cierra mucho, ¿Porque pasaría esto?

**Comment by nicosoutn2014** [comment]
Osea no modificas el chofer en si sino el chofer q tiene asignado ese
vehículo, el turno q tiene asignado ese vehículo y el modelo ahora me fijo
no me acuerdo por qué

El 12 jun. 2017 2:23 p. m., "Andres Martinez" <notifications@github.com>
escribió:

Que al modificar un campo de la tabla se actualicen todos no me parece mal,
es más fácil. Ahora, que al editar el vehículo se modifique el chofer el
turno y el modelo no me cierra mucho, ¿Porque pasaría esto?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/andresemartinez/gdd-UberFrba/issues/1#issuecomment-307857831>,
or mute the thread
